modclub-app/modclub_src

src/modclub/main.mo
src/modclub_assets/src/components/app/profile/Activity.tsx
src/modclub_assets/src/components/app/profile/ActivityTable.tsx

* Reduce function omitted
* Poh taken into consideration
* fetch minimized
[d428bcb9-90bb-4f68-bf07-5af687b221ff.webm](https://github.com/modclub-app/modclub_src/assets/82664734/43a296b3-542d-4086-b843-23735d91620c)

MOD-667 sorting activities refactored

---

.github/workflows/create_proposal.yml

---
Disables the backup step that is preventing deployment. This will be re-enabled after a fix.

chore: [] Disable Backup in create_proposal

---

scripts/deployment/build_utils.sh

---
Removed the typo in the previous commit.

Typo of decideid

---

scripts/deployment/build_utils.sh
scripts/infra/up_infra.sh

Quick fix on canister creation

---

src/decideid_assets/src/components/app/Main.tsx
src/decideid_assets/src/components/auth/new_profile/NewProfile.tsx
src/decideid_assets/src/components/external/landing/Landing.tsx
src/decideid_assets/src/components/header/Header.tsx
src/decideid_assets/src/components/routers/Authed.tsx
src/decideid_assets/src/hooks/useProfile.tsx
src/decideid_assets/src/index.tsx

---
Add simple UI for registration.

MOD-724 Decideid Registration UI

---

src/modclub_assets/src/components/app/tasks/Task.tsx
src/modclub_assets/src/components/app/tasks/TaskConfirmationModal.tsx
src/modclub_assets/src/utils/gtm.ts

MOD-734: added task vote event

---

src/decideid_assets/app/components/auth/Logout.tsx
src/decideid_assets/app/components/auth/new_profile/NewProfile.tsx
src/decideid_assets/app/hooks/useProfile.tsx

---
Implemented "optimistic mutation" when creating new profile.
I didn't directly utilize React Query for this implementation. Instead, I introduced an additional layer within the NewProfile component to enhance the user experience.
-
- [x ] New feature
- [x ] I have performed a self-review of my own code.
-
-

feat: [] refactored Optimistic mutation

---

canister_ids.json

Add assets ids for decideid

---

.github/workflows/PR_CI_build.yml
.github/workflows/PR_CI_test.yml
.github/workflows/create_proposal.yml
.github/workflows/deploy_dev.yml
.github/workflows/deploy_qa.yml

---
See https://forum.dfinity.org/t/the-dfx-version-manager-dfxvm-version-1-0-0-is-released/27720

Fix dfx installation

---

scripts/deployment/deployment_utils.sh

Deploy decideid assets on ic network

---

canister_ids.json
scripts/deployment/deployment_utils.sh
src/common/types.mo
src/modclub/main.mo
src/modclub/msgInspectTypes.mo
src/modclub/types.mo
src/modclub_assets/src/components/app/profile/Activity.tsx
src/modclub_assets/src/utils/util.ts
webpack.config.cjs

---
Verified Credentials for Proof of Humanity
[*Link to the issue](https://linear.app/modclub/issue/MOD-751/finish-vc-work-so-that-it-works-with-existing-modclub)
Manual

feat: [] VC implementation

---

src/modclub_assets/src/components/app/profile/Activity.tsx
yarn.lock

MOD-794: update Verified Credentials design in profile

---

src/modclub/main.mo

---
Reducing reputation if user unstake more than MinStake amount
https://linear.app/modclub/issue/MOD-820/refactor-reputation-reduce-businesslogic
manual
--

fix: [MOD-820] Reduce reputation on unstake

---

src/modclub/main.mo

fix: [MOD-820] repputation reduce on unstake

---

scripts/deployment/deployment_utils.sh

Fix init_canisters

---

scripts/deployment/deployment_utils.sh

Fix configurePohForProvider

---

scripts/deployment/deployment_utils.sh

---
See https://github.com/modclub-app/modclub_src/actions/runs/8476517705/job/23226157063. 

Fix 'unexpected IDL type when parsing Nat'

---

.github/workflows/PR_CI_build.yml
.github/workflows/PR_CI_test.yml
.github/workflows/create_proposal.yml
.github/workflows/deploy_qa.yml

Fix mops installation

---

.github/workflows/deploy_dev.yml

Fix mops in dev pipeline

---

.github/workflows/PR_CI_build.yml
.github/workflows/PR_CI_test.yml
scripts/deployment/deployment_utils.sh
scripts/deployment/gh_actions_deploy.sh
src/authentication/main.mo

---
Async Publish for EventBus on Auth canister
--
manual
--

chore: [] EventBus improvements

---

scripts/deployment/deployment_utils.sh

---
Fixed duplicated output for deployment script.
--
manual
--

fix: [] duplicated output.

---

dfx.json
scripts/build/gen_files_by_env.cjs
scripts/infra/up_infra.sh
scripts/seeds/gen_content.sh
scripts/seeds/gen_provider.sh
scripts/utils.sh
src/declarations/wallet/index.js
src/declarations/wallet/wallet.did
src/declarations/wallet/wallet.did.d.ts
src/declarations/wallet/wallet.did.js

---
Remove _QA from local canisters. They should be called just the canister name
https://linear.app/modclub/issue/MOD-1307/remove-qa-from-local-canisters-they-should-be-called-just-the-canister
Ensure all tests(automatic) are passing

MOD-1307 Remove qa from canister names
